### ISSUE TITLE
BadRequestError

### ISSUE THREAD

**Issue by TheAtomicNord** [lextoumbourou/PyWit#7]
Hello,

First of all thanks for all your hard work on this awesome module.
I love wit and was so excited to use it with python. However, when running the "Basic Usage" example, I get a BadRequestError: "Something went wrong. We've been notified." I'm really not sure how to fix this and I really want to use wit.

If you have any idea how to fix this I'd really appreciate it. Thanks!

**Comment by lextoumbourou** [comment]
Yo homie,

Thanks for the bug report. I'll look into it.

FYI, my library has kinda been deprecated in favour of the [official Python SDK](https://github.com/wit-ai/pywit). Can you check it out and see if it meets your needs? I'll still fix the bug tho.

Thanks again,

Lex

**Comment by lextoumbourou** [comment]
@TheAtomicNord, whoops, I kinda forgot about this one... Sorry! It should be all fixed in ``v0.4.0``, just ``pip install PyWit --upgrade``.

:heart:
